# Specify the number of spaces per indentation-level.
tabWidth: 2

# Use single quotes instead of double quotes.
singleQuote: true

# Print semicolons at the ends of statements.
semi: true

# prose wrap helps formatting Markdown and YAML
proseWrap: always

# vim-prettier has its own defaults, so we need to reset anything that doesn't match
trailingComma: es5
