# Specify the number of spaces per indentation-level.
tabWidth: 2

# Use single quotes instead of double quotes.
singleQuote: true

# Print trailing commas wherever possible when multi-line (A single-line array, for example, never gets trailing commas).
trailingComma: "none"
